name: Run Python Linting

on: [push, pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          pip install isort
          isort --check-only --diff .

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run black check
        uses: jpetrucciani/black-check@master
        with:
          path: "."

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff check
        uses: jpetrucciani/ruff-check@main
        with:
          path: "."
