name: Run Python Linting

on: [push, pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: isort/isort-action@v1
        with:
          configuration: --check-only --diff --profile black

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run black check
        uses: jpetrucciani/black-check@master

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff check
        uses: jpetrucciani/ruff-check@main

  test:
    needs: [isort, black, ruff]
    runs-on: ubuntu-latest

    # if: github.ref == 'refs/heads/sub'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pytest pytest-md pytest-emoji pytest-cov requests

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          click-to-expand: false
          report-title: '測試報告'

      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          create-new-comment: true
          badge-title: "pytest"
          junitxml-path: ./pytest.xml
          junitxml-title: "pytest 總結"
          pytest-xml-coverage-path: ./pytest-coverage.xml
          title: "pytest 測試覆蓋率 (點擊打開)"


