name: Run Python Linting

on: [push, pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: isort/isort-action@v1
        with:
          configuration: --check-only --diff --profile black

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run black check
        uses: jpetrucciani/black-check@master

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff check
        uses: jpetrucciani/ruff-check@main

  test:
    needs: [isort, black, ruff]
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/sub'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies and Run Tests
        run: |
          pip install pytest pytest-cov requests
          pytest --junitxml=coverage.xml --cov-report=term-missing:skip-covered --cov tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          pytest-xml-coverage-path: ./coverage.xml
          title: My Coverage Report Title
          badge-title: My Badge Coverage Title
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          unique-id-for-comment: python3.8
          junitxml-path: ./pytest.xml
          junitxml-title: My JUnit Xml Summary Title

