name: Run Python Linting

on: [push, pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run isort check
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile black --thirdparty pytest"

      - name: Run black check
        uses: jpetrucciani/black-check@master
        with:
          path: "."

      - name: Run ruff check
        uses: jpetrucciani/ruff-check@main
        with:
          path: "."

#  black:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Run black check
#        uses: jpetrucciani/black-check@master
#        with:
#          path: "."

#  ruff:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Run ruff check
#        uses: jpetrucciani/ruff-check@main
#        with:
#          path: "."
