name: Run Python Linting

on: [push, pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: isort/isort-action@v1
        with:
          configuration: --check-only --diff --profile black

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run black check
        uses: jpetrucciani/black-check@master

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff check
        uses: jpetrucciani/ruff-check@main

  test:
    needs: [isort, black, ruff]
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/sub'
    steps:
      - uses: actions/checkout@v4

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./123.xml
