name: Run Python Lint and Test

on:
  push:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout file
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_lint.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install lint dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements_lint.txt

      - name: Run isort check
        run: isort --check-only --diff --profile black .

      - name: Run black check
        run: black --check .

      - name: Run ruff check
        run: ruff check .

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout file
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest dependencies
        run: |
          pip install pytest pytest-md pytest-emoji pytest-cov requests

      - name: Run pytest and Export pytest report
        uses: pavelzw/pytest-action@v2
        with:
          click-to-expand: false
          report-title: '測試報告'

      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          create-new-comment: true
          badge-title: "pytest"
          junitxml-path: ./pytest.xml
          junitxml-title: "pytest 總結"
          pytest-xml-coverage-path: ./pytest-coverage.xml
          title: "pytest 測試覆蓋率 (點擊打開)"




