name: new linter

on: push

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "."
          use-isort: false
          use-black: false
          extra-isort-options: "--check-only --diff --profile black --thirdparty pytest"