name: Run Tests

on:
  workflow_run:
    workflows: ["Run Python Linting"]
    types:
      - completed
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies and Run Tests
        run: |
          pip install pytest pytest-cov requests
          pytest