name: pytest-coverage-comment
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Build coverage file
        run: |
          pytest --cov-report "xml:coverage.xml" --cov=src tests/

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./path-to-file/pytest-coverage.txt
          pytest-xml-coverage-path: ./path-to-file/coverage.xml
          title: My Coverage Report Title
          badge-title: My Badge Coverage Title
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          unique-id-for-comment: python3.8
          junitxml-path: ./path-to-file/pytest.xml
          junitxml-title: My JUnit Xml Summary Title