name: Run Tests

on:
  # pull_request:
  workflow_run:
    workflows: ["Run Python Linting"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pytest pytest-md pytest-emoji pytest-cov requests

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          click-to-expand: false
          report-title: '測試報告'

      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          create-new-comment: true
          badge-title: "pytest"
          junitxml-path: ./pytest.xml
          junitxml-title: "pytest 總結"
          pytest-xml-coverage-path: ./pytest-coverage.xml
          title: "pytest 測試覆蓋率 (點擊打開)"
