name: pytest-coverage-comment
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov requests

      - name: Build coverage file
        run: |
          pytest --cov-report "xml:pytest-coverage.xml" --cov tests/

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./pytest-coverage.xml
          title: "pytest 測試報告"
          badge-title: "pytest coverage"
          junitxml-path: ./pytest-coverage.xml
          junitxml-title: My JUnit Xml Summary Title