name: Run Ruff Check

on:
  push:
    branches:
      - main

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run isort lint
        uses: isort/isort-action@v1
        with:
            configuration: "pyproject.toml"

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff check
        uses: jpetrucciani/ruff-check@main
        with:
          path: "."