name: Run Python Lint

on: [push]

jobs:
  lint:
    name: Ruff Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jpetrucciani/ruff-check@main
        with:
          path: "."
